{
 "title": "miktik monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance_name", "label": "Instance name", "query": { "query": "label_values(routerboard_name)" } }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik__connection__status__{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "Package version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_router_status{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{router_status_version}}"
    }
   ]
  },
  {
   "title": "Routerboard version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_routerboard_status{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{routerboard_status_current_firmware}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "miktik_router_status_cpu_load{routerboard_name=\"$instance_name\"}",
     "legendFormat": "CPU utilization"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(miktik_router_status_total_memory{routerboard_name=\"$instance_name\"}-miktik_router_status_free_memory{routerboard_name=\"$instance_name\"})/miktik_router_status_total_memory{routerboard_name=\"$instance_name\"}",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_router_status{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{﻿router_status_uptime}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(miktik_router_status_total_hdd_space{routerboard_name=\"$instance_name\"}-miktik_router_status_free_hdd_space{routerboard_name=\"$instance_name\"})/miktik_router_status_total_hdd_space{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_router_status{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "Identity name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_identity{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{identity_name}}"
    }
   ]
  },
  {
   "title": "CPU arcitecture",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_router_status{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{router_status_cpu}}"
    }
   ]
  },
  {
   "title": "Cores number",
   "type": "stat",
   "description": "CPU cores number",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_router_status{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{router_status_cpu_count}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(miktik_router_status_total_memory{routerboard_name=\"$instance_name\"}-miktik_router_status_free_memory{routerboard_name=\"$instance_name\"})/miktik_router_status_total_memory{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_router_health_temperature{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_router_health_voltage{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_router_status{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{router_status_cpu_frequency}}MHz"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Internet download",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "miktik_interfaces_traffic_rx_bits_per_second{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{interfaces_traffic_name}}"
    }
   ]
  },
  {
   "title": "Internet upload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "miktik_interfaces_traffic_rx_bits_per_second{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{interfaces_traffic_name}}"
    },
    {
     "expr": "miktik_interfaces_traffic_tx_bits_per_second{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{interfaces_traffic_name}}"
    }
   ]
  },
  {
   "title": "Queue graph download",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "miktik_queue_rate_0{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{queue_name}} download"
    }
   ]
  },
  {
   "title": "Queue graph upload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "miktik_queue_rate_1{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{queue_name}} download"
    }
   ]
  },
  {
   "title": "Internet latency ",
   "type": "graph",
   "description": "Cloudflare ping latency",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "miktik_ping_test_time_0{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "Internet usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_traffic_counter_bytes{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "Ipv6 internet usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_traffic_counter_v6_bytes{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Enabled interfaces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "miktik_interfaces_disabled{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{interfaces_name}}"
    }
   ]
  },
  {
   "title": "Active interfaces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "miktik_interfaces_running{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{interfaces_name}}"
    }
   ]
  },
  { "title": "Addresses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Routerboard addresses",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "miktik_address_info{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "dhcp server",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "miktik_dhcp_leases{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  { "title": "Wireless", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Wireless clients",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "miktik_wireless_clients{routerboard_name=\"$instance_name\"}"
    }
   ]
  },
  {
   "title": "Wireless clients' noise",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "miktik_wireless_clients_signal_strength_0{routerboard_name=\"$instance_name\"}",
     "legendFormat": "{{wireless_clients_comment}} {{wireless_clients_mac_address}}"
    }
   ]
  },
  {
   "title": "Amount of clietns",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(miktik_wireless_clients_signal_strength_0{routerboard_name=\"$instance_name\"})",
     "legendFormat": "Clients amount"
    }
   ]
  },
  {
   "title": "CAPsMAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wireless cap clients",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "expr": "miktik_cap_clients{routerboard_name=\"$instance_name\"}"
      }
     ]
    },
    {
     "title": "Wireless cap clients",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "miktik_cap_instances{routerboard_name=\"$instance_name\"}"
      }
     ]
    },
    {
     "title": "Amount of access point",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(miktik_cap_instances{routerboard_name=\"$instance_name\"})",
       "legendFormat": "Clients amount"
      }
     ]
    },
    {
     "title": "Amount of clietns",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(miktik_cap_clients{routerboard_name=\"$instance_name\"})",
       "legendFormat": "Clients amount"
      }
     ]
    },
    {
     "title": "Wireless clients' noise",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "miktik_cap_clients_rx_signal{routerboard_name=\"$instance_name\"}",
       "legendFormat": "{{cap_clients_comment}} {{cap_clients_mac_address}}"
      }
     ]
    }
   ]
  }
 ]
}